---
ID: "b01dfd36-d108-4cc9-b0e7-397b2a36a989"
Parent: "87b253eb-2f25-46a3-b27b-51d4ce85ac7b"
Template: "87b253eb-2f25-46a3-b27b-51d4ce85ac7b"
Path: /sitecore/templates/Modules/GenAI/Settings/GenAI Settings/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240517T124138Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "53b1736e-a862-4bd0-9241-0467d55e94dd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rpeplau@arke.com
    - ID: "d48c2e63-7717-457f-9625-c73473322e0b"
      Hint: Model
      Value: "{5AD186B0-FDBC-4B34-9F71-17BC8010B5EC}"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240903T130747Z
