---
ID: "a184f4c7-7c88-4912-95b4-95a925e2ca4b"
Parent: "87b253eb-2f25-46a3-b27b-51d4ce85ac7b"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Modules/GenAI/Settings/OpenAI Settings/OpenAI Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240517T124411Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d0dc1589-6ab0-450d-9231-b8f591bb922b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240827T173512Z
